import { useEffect, useState } from 'react'
import './DevTools.css'

export const DevTools = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const [storage, setStorage] = useState<string | null>(null)
  useEffect(() => {
    chrome.storage.local.get(null, (result) => {
      setStorage(JSON.stringify(result, null, 2))
    })
  })

  const onDeleteStorage = () => {
    chrome.storage.local.clear(() => {
      setStorage(null)
    })
  }

  return (
    <main>
      <h3>DevTools Page</h3>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <h3>Storage</h3>
      <pre>{storage}</pre>
      <button onClick={onDeleteStorage}>Delete Storage</button>
    </main>
  )
}

export default DevTools
